apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spot-hinta
      language: go
  template:
    metadata:
      labels:
        app: spot-hinta
        language: go
    spec:
      containers:
      - name: go-app
        image: amit517/spot-hinta-go:latest
        ports:
        - containerPort: 8080