apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config

data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        upstream backend_prices {
            # Define the load-balancing backend for /get_prices path
            server python-app:5000;   # Python Flask app container (internal Docker name)
            server go-app:8080;       # Go app container (internal Docker name)
        }

        server {
            listen 80;  # Listen on port 80 for HTTP requests

            # Serve the main index page from the Python app
            location / {
                proxy_pass http://python-app:5000;  # Always proxy / to the Python app
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Load-balance /get_prices between Python and Go apps
            location /get_prices {
                proxy_pass http://backend_prices;  # Use the load-balanced backend
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Optional: Add logging for easier debugging
            access_log /var/log/nginx/access.log;
            error_log /var/log/nginx/error.log;
        }
    }