apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer  # Use NodePort or ClusterIP depending on your requirements
  ports:
    - port: 8081
      targetPort: 80  # Maps to the container port
      nodePort: 30001   # Specific port to use
  selector:
    app: nginx  # Label to select Pods
