apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spot-hinta
      language: python
  template:
    metadata:
      labels:
        app: spot-hinta
        language: python
    spec:
      containers:
      - name: python-app
        image: amit517/spot-hinta-python:latest
        ports:
        - containerPort: 5000