apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if you need external access
  ports:
    - port: 5000           # Service port
      targetPort: 5000     # Container port
  selector:
    app: spot-hinta        # This should match the Deployment labels
    language: python       # Optional, but can be included for more specific matching
